### PR TITLE
adding public_ip_joined

### PR DESCRIPTION
**Pull request by MacFlurry**
public_ip_joined added 
POWERLEVEL9K_PUBLIC_IP_HOST="http://ident.me added

### CODE REVIEW

**Comment by mavam** [comment]
Thanks for your contribution.

Since the amount of information in the shell prompt is a somewhat subjective matter, I'd rather make this configurable (e.g., via `.zenv.local`) as opposed to hardcoding it. Can you refactor the patch so that the prompt environment variables can be overridden on a per-user basis?

**Comment by MacFlurry** [comment]
Oh yeah, it's a good idea!. let me do it

**Comment by MacFlurry** [comment]
by moving the changes to zshrc.local, I was able to get the same result. so I no longer need to change the.zshrc file. you can ignore the "PR".

on the other hand, could you show me the variables for the public ip? because I have a light background that is not pretty.

[screen Shot](https://imgur.com/a/A0I7Ma9)

**Comment by MacFlurry** [comment]
Ok I figured it out. 

I can close this PR, no longer need it. I'll override on `zshrc.local`

thanks a lot ;-)

**Comment by mavam** [comment]
>  could you show me the variables for the public ip?

I don't know them by heart, but I'm sure the Powerlevel9k documentation lists those. If not, I'd do a bit of trial and error based on the variable names from other segments.

**Pull request closed without merging**
